language: java
sudo: false

services:
  - docker
  
before_script:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker-compose up -d

cache:
  directories:
  - $HOME/.m2

jobs:
  include:
  - stage: test
    jdk: oraclejdk8
    script: mvn clean install -Dmaven.test.skip=true

branches:
  only:
  - master
  
after_script:
  - docker-compose down
